src/Entity/Publication.php
<?php

namespace App\Entity;
use App\entity\User;
use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=PublicationRepository::class)
 */
class Publication 
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="1", minMessage="Vous devez entre votre publication")
     */
    private $publication_text;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="publication", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomUser;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PrenomUser;

    /**
     * @ORM\OneToMany(targetEntity=PostLike::class, mappedBy="post")
     */
    private $likes;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?string
    {
        return $this->id_user;
    }

    public function setIdUser(string $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getPublicationText(): ?string
    {
        return $this->publication_text;
    }

    public function setPublicationText(string $publication_text): self
    {
        $this->publication_text = $publication_text;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPublication($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPublication() === $this) {
                $comment->setPublication(null);
            }
        }

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getNomUser(): ?string
    {
        return $this->nomUser;
    }

    public function setNomUser(string $nomUser): self
    {
        $this->nomUser = $nomUser;

        return $this;
    }

    public function getPrenomUser(): ?string
    {
        return $this->PrenomUser;
    }

    public function setPrenomUser(string $PrenomUser): self
    {
        $this->PrenomUser = $PrenomUser;

        return $this;
    }

    /**
     * @return Collection|PostLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(PostLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setPost($this);
        }

        return $this;
    }

    public function removeLike(PostLike $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getPost() === $this) {
                $like->setPost(null);
            }
        }

        return $this;
    }
    /**
     * @param User $user
     * @return boolean
     */
    public function isLikedByUser(User $user) :bool{
foreach($this->likes as $like){
    if($like->getUser()===$user) return true;
}
return false;
    }
}

src/Form/PublicationType.php
<?php

namespace App\Form;

use App\Entity\Publication;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PublicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Publication::class,
        ]);
    }
}

src/Controller/PublicationController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\PostLike;
use App\Entity\Publication;
use App\Form\Publication2Type;
use App\Repository\PublicationRepository;
use App\Repository\PostLikeRepository;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;

/**
 * @Route("/publication")
 */
class PublicationController extends AbstractController
{
    /**
     * @Route("/", name="publication_index", methods={"GET"})
     */
    public function index(PublicationRepository $publicationRepository  ): Response
    {
        
        return $this->render('publication/index.html.twig', [
            'publications' => $publicationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="publication_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $publication = new Publication();
        $form = $this->createForm(Publication2Type::class, $publication);
        $form->handleRequest($request);
        $user = $this->getUser()->getId();
    
        if ($form->isSubmitted() && $form->isValid()) {
            $publication->setIdUser($user);
            $publication->setNomUser($this->getUser()->getNom());
            $publication->setPrenomUser($this->getUser()->getPrenom());
            $publication->setImg("https://i.imgur.com/gFaPbi6_d.webp?maxwidth=760&fidelity=grand");
           
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($publication);
            $entityManager->flush();

            return $this->redirectToRoute('publication_index');
        }

        return $this->render('publication/new.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="publication_show", methods={"GET"})
     */
    public function show(Publication $publication): Response
    {
        return $this->render('publication/show.html.twig', [
            'publication' => $publication,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="publication_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Publication $publication): Response
    {
        $form = $this->createForm(Publication2Type::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('publication_index');
        }

        return $this->render('publication/edit.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="publication_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Publication $publication,PostLikeRepository $likeRepo): Response
    {

      
        if ($this->isCsrfTokenValid('delete'.$publication->getId(), $request->request->get('_token'))) {
            $mylikes=$likeRepo->findBy([
                'post'=>$publication,
                ]);
                $entityManager = $this->getDoctrine()->getManager();
                foreach ($mylikes as $likeee) {
                    $entityManager->remove($likeee);  
                   
                }
                $entityManager->flush(); 
                $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($publication);
            $entityManager->flush();
        }
        
    
        return $this->redirectToRoute('publication_index');
    }
    
    /**
     * @Route("/{id}/like",name="publication_like")
     * 
     * @param PostLikeRepository $likeRepo
     * @param Publication $publication
     * @param \Symfony\Component\HttpFoundation\Response
     */
    public function like(Publication $publication, PostLikeRepository $likeRepo):
    Response{
        $user=$this->getUser();
if(!$user)return $this->json([
    'code'=>403,
    'message'=>"Unauthorized"
],403);
if($publication->isLikedByUser($user)){
    $like=$likeRepo->findOneBy([
        'post'=>$publication,
        'user'=>$user
    ]);
    $entityManager = $this->getDoctrine()->getManager();
    $entityManager->remove($like);
    $entityManager->flush();
    return $this->json([
        'code'=>200,
        'message'=> 'like bien supprimé',
        'likes'=>$likeRepo->count(['post'=>$publication])
    ],200);
}
$like =new PostLike();
$like->setPost($publication)
     ->setUser($user);
    $entityManager = $this->getDoctrine()->getManager();
    $entityManager->persist($like);
    $entityManager->flush();

return $this->json(['code'=>200,
'message'=>'like bien ajouté',
'likes'=>$likeRepo->count(['post'=>$publication])],200);
    }
}

templates/publication/_delete_form.html.twig
<form method="post" action="{{ path('publication_delete', {'id': publication.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">

    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ publication.id) }}">
    <button class="btn btn-danger">Supprimer <i class="fas fa-times"></i></button>
   
</form>

templates/publication/_form.html.twig
{{ form_start(form) }}
 
      {{ form_row(form.publication_text,{'attr':{'class':'form-control space' },'label':'Publication'}) }} 
      
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/publication/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Publication{% endblock %}

{% block section %}
<section class="mypage"></section>
<div class="head-mybody">
<a href="{{ path('publication_index') }}"><i class="fas fa-arrow-left"></i> Retour</a>
    <h1>Changer la Publication</h1>

    {{ include('publication/_form.html.twig', {'button_label': 'Update'}) }}
    {% if publication.getIdUser() == app.user.id  %}
    

    {# {{ include('publication/_delete_form.html.twig') }} #}
    {% endif %}
    </div>
{% endblock %}

templates/publication/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publication index{% endblock %}

{% block section %}
<section class="mypage"></section>
<div class="head-mybody">
    <h1>Publication</h1>
  
    <a class="btn btn-primary"href="{{ path('publication_new') }}"> <i class="fas fa-plus"></i> Ajouter publication</a>
 
    </div>
<section class="myPublication">



{% for publication in publications %}   
<div class="container">


<div class="row">
<div class="col-sm-1">
<div class="thumbnail">
<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
</div><!-- /thumbnail -->
</div><!-- /col-sm-1 -->


<div class="col-sm-5">

<div class="panel panel-default">

<div class="panel-heading">
<strong>{{ publication.nomUser }} {{ publication.PrenomUser }}</strong> 
{# <span class="text-muted">commented 5 days ago</span> #}
 <div class="btn-delete-my"> {% if publication.getIdUser() == app.user.id  %}
          
            {{ include('publication/_delete_form.html.twig') }}
        {% endif %}
        </div>
</div>
<div class="panel-body">
{{ publication.publicationText |replace({'bro': '***', 'tit': "***"})}}
</div><!-- /panel-body -->
<div class=" panel-default">
{# <a href="{{ path('publication_show', {'id': publication.id}) }}" class="card-link">Show</a> #}
        <a href="{{ path('publication_like',{'id':publication.id})}}" class="btn btn-link js-like">
        {% if app.user and publication.isLikedByUser(app.user) %}
        <i class="fas fa-thumbs-up"></i>
        {% else %}
         <i class="far fa-thumbs-up"></i>
        {% endif %}
    <span class="js-likes">{{ publication.likes | length }}</span>
 
    <span class="js-label">J'aime</span>
    </a>
        {% if publication.getIdUser() == app.user.id  %}
            <a href="{{ path('publication_edit', {'id': publication.id}) }}" class="card-link">Changer <i class="fas fa-edit btn-link"></i></a> 

           
        {% endif %}
        </div>
</div><!-- /panel panel-default -->

</div><!-- /col-sm-5 -->
 

</div><!-- /row -->

</div><!-- /container -->




        {% endfor %}
</section>


{% endblock %}
{% block js3 %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>

function onClickbtnLike(event){
    event.preventDefault();
 
    const url = this.href;
    const spanCount=this.querySelector('span.js-likes');
    const icone=this.querySelector('i');
    axios.get(url).then(function(response){
       
        spanCount.textContent=response.data.likes;
        if(icone.classList.contains('fas')) 
        icone.classList.replace('fas','far')
        else icone.classList.replace('far','fas');
    }).catch(function(error){
        if(error.response.status===403){
            window.alert("aamel l auth");
        }else
          window.alert("moushkla");
    })
}


document.querySelectorAll('a.js-like').forEach(function(link){
    link.addEventListener('click',onClickbtnLike);
})

</script>
{% endblock %}

templates/publication/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Publication{% endblock %}
{% block section %}
<section class="mypage"></section>
<div class="stmeformlpub">
<a href="{{ path('publication_index') }}"><i class="fas fa-arrow-left"></i> Retour</a>
    <h1>Creer une publication</h1>

    {{ include('publication/_form.html.twig') }}

    
    </div>
{% endblock %}

templates/publication/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publication{% endblock %}

{% block section %}
<section class="mypage"></section>
    <h1>Publication</h1>

    <table class="table">
        <tbody>
           
            <tr>
                <th>Publication_text</th>
                <td>{{ publication.publicationText }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('publication_index') }}">back to list</a>


    {% if publication.getIdUser() == app.user.id  %}
        <a href="{{ path('publication_edit', {'id': publication.id}) }}">edit</a>
        {{ include('publication/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}